server {
    listen 80;
    listen [::]:80;
    server_name matroid-garden.com www.matroid-garden.com;
    return 301 https://matroid-garden.com$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name www.matroid-garden.com;

    ssl_certificate /etc/letsencrypt/live/matroid-garden.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/matroid-garden.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://matroid-garden.com$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name matroid-garden.com;

    # Fano deployment point on small:
    # - downloads
    root /var/www/universal-life-protocol-downloads/current;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/matroid-garden.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/matroid-garden.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    add_header X-Content-Type-Options nosniff always;

    location / {
        autoindex on;
        try_files $uri $uri/ =404;
    }
}
